language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t kjarmusz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kjarmusz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  regoion: eu-west-2
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-189189131966"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY